#! /bin/sh
#
# Y88b           .d8888b. Y88b   d88P 8888888b.          
#  Y88b         d88P  Y88b Y88b d88P  888   Y88b         
#   Y88b        888    888  Y88o88P   888    888         
#    Y88b       888          Y888P    888   d88P         
#    d88P       888           888     8888888P"          
#   d88P        888    888    888     888                
#  d88P         Y88b  d88P    888     888                
# d88P           "Y8888P"     888     888       88888888 
#
# Author: Cyril PARODI   
# https://github.com/crlparodi/dotfiles  

# Keymap and bindings
sxhkd &
setxkbmap -layout fr &

# Startup
~/.config/scripts/startup.sh

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Integers
bspc config border_width			  	1
bspc config window_gap					0

# Toggles
bspc config focus_follows_pointer     	true
bspc config borderless_monocle		  	true
bspc config gapless_monocle           	true
bspc config single_monocle				true
bspc config remove_unplugged_monitors	true

# Colors of bspwm
bspc config focused_border_color    "#FAA41A"
bspc config normal_border_color		"#242424"
