#! /bin/sh

sxhkd &
setxkbmap -layout fr &

# Startup
nitrogen --restore &
~/.config/scripts/launch_conky.sh
~/.config/scripts/launch_dunst.sh
~/.config/scripts/launch_polybar.sh

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Integers
bspc config border_width			  	1
bspc config window_gap					0

# Toggles
bspc config focus_follows_pointer     	true
bspc config borderless_monocle		  	true
bspc config gapless_monocle           	true
bspc config single_monocle				true
bspc config remove_unplugged_monitors	true

# Colors of bspwm
bspc config focused_border_color    "#FFFFFF"
bspc config normal_border_color		"#000000"
